---
title: "BDA 503 Fall 2023"
toc: false
---

# Week 5

This week's lecture is more about some intermediate topics about data processing/manipulation. We will mainly learn about joins, long/wide tables. In addition, if time permits, some data parsing from web site sources.

- [dplyr joins](https://stat545.com/join-cheatsheet.html)
    - [Mini live lecture](https://berkorbay.github.io/book-of-eda/dplyr-joins.html)
- [Brief tutorial on pivot_longer/pivot_wider](https://pjournal.github.io/boun-ie48a/files/short_tutorial_on_pivot_wider_longer.html)  
- (if time permits) [rvest](https://berkorbay.github.io/book-of-eda/rvest.html) 

# Week 4

Guest Lecture: [Burak Yitgin](https://www.linkedin.com/in/burakyitgin/) - Business Development Manager and Senior Consultant at APLUS Enerji

This week's lecture is focused on **Shiny**, an R package to develop interactive dashboards and web pages. Shiny is also available for [Python](https://shiny.rstudio.com/py/), so what you learn here is transferrable to Python.

- [Introduction to Shiny (official tutorial)](https://shiny.rstudio.com/tutorial/)
    - [Showcase Gallery](https://shiny.rstudio.com/gallery/)
    - [Cheat Sheet](https://shiny.rstudio.com/articles/cheatsheet.html)
    - [shinyapps.io](https://shinyapps.io)
- [Example app (Movies)](https://gist.github.com/berkorbay/5793188b7ebfe013ce64703179f9aa01).

:::{.callout-tip title="Bonus Material" collapse="true"}
**Additional resources**

+ [shinylive](https://shiny.posit.co/py/docs/shinylive.html)
+ [shinylive R Package](https://posit-dev.github.io/r-shinylive/)
+ [Mastering Shiny](https://mastering-shiny.org/)  
+ [`golem` R package](https://thinkr-open.github.io/golem/)
+ [Engineering Shiny (advanced)](https://engineering-shiny.org/)
+ [`shinydashboard` R package](https://rstudio.github.io/shinydashboard/) for additional dashboard capabilities.
+ [`shinyMobile` R package](https://rinterface.github.io/shinyMobile/) for mobile app-like capabilities.
:::

::: {.callout-caution title="In-Class Exercise (Individual)" collapse="false"}
Build a `shiny` app using your proposed data sets in Assignment 1 and deploy it to [shinyapps.io](https://shinyapps.io). Add a link to your Shiny app in your Progress Journal as In-class assignment 3. 
:::


# Week 3

Guest Lecture: [Ahmet Tunçel](https://www.linkedin.com/in/ahmettuncel/) - Senior Data Architect Manager at Sky Deutschland GmbH

- [Introduction to ggplot2](./ggplot2.html)
- [ggplot2 Lecture Notes](https://berkorbay.github.io/book-of-eda/ggplot2.html)
- [ggplot2 official page and cheat sheet](https://ggplot2.tidyverse.org/)

::: {.callout-tip title="Bonus Material" collapse="true"}
- *Supplementary resources*
    - [ggplot2 Cheat Sheet](https://www.maths.usyd.edu.au/u/UG/SM/STAT3022/r/current/Misc/data-visualization-2.1.pdf)
    - [Step by step ggplot2 introduction (5min)](https://www.youtube.com/watch?v=FdVy57oGJuc)
    - [{ggplot2} ile Veri Görselleştirme (Turkish)](https://www.youtube.com/watch?v=QB8OXAzL8QE)
    - [Improve ggplot2 visualization](https://www.youtube.com/watch?v=qnw1xDnt_Ec)
    - [Detailed YouTube course](https://www.youtube.com/playlist?list=PLtL57Fdbwb_C6RS0JtBojTNOMVlgpeJkS)
- Voluntary Self Exercise (YOK Foreign Students by Nationality Data Set)
    - Download Data ([xlsx](https://github.com/berkorbay/datasets/raw/master/foreign_students/foreign_students_by_nationality_2021_2022.xlsx))
    - Starter Code ([gist](https://gist.github.com/berkorbay/f394bf2ea8775cf7b5316aeafd27c482#file-foreign_students_report_starter_code-qmd))
:::

::: {.callout-caution title="In-Class Exercise (Individual)" collapse="false"}
Update your analysis using both `dplyr` and `ggplot2` on your proposed data sets in Assignment 1. Open a new \.qmd document named `inclass2.qmd` and make it visible on your PJ (update `_quarto.yml` file). (DO NOT TOUCH `inclass1.qmd`)
:::

::: {.callout-caution title="Group Assignment (Tentative) Deadline: Nov 23, 18:30" collapse="false"}
[Global Dietary Database](https://globaldietarydatabase.org) provides a wealth of data regarding nutrition intake of a large number of countries. Your assignment is to prepare a brief exploratory data analysis on **Vitamin B12 intake of Former Soviet Union countries** using `dplyr` and `ggplot2`. Relevant subset and explanations are given in the below links.

+ [Data set](https://raw.githubusercontent.com/berkorbay/datasets/master/gdd/gdd_b12_levels.csv)
+ [Codebook (Explanations)](https://github.com/berkorbay/datasets/raw/master/gdd/GDD%202018%20Codebook_Jan%2010%202022.xlsx)
:::


# Week 2

- [Introduction to dplyr](./dplyr.html)
- [dplyr Lecture Notes](https://berkorbay.github.io/book-of-eda/dplyr.html)
- *Supplementary resources*
    - [dplyr Cheat Sheet](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-transformation.pdf)
    - [Book: R for Data Science](https://r4ds.had.co.nz/) by Hadley Wickham & Garrett Grolemund
    - [dplyr with Election Data](https://pjournal.github.io/files/dplyr_elections.html)


::: {.callout-tip title="Bonus Material" collapse="true"}
- Turkish dplyr R resource: [Eskişehir R User Group](https://www.youtube.com/watch?v=bzrP5bOIyYI)
- Exercise on basic Stock Fundamentals data. Run the following code to get the data.
```{r}
#| eval: false
#| echo: true

library(tidyverse) ## or library(dplyr)
tf <- tempfile()
download.file("https://github.com/berkorbay/datasets/raw/master/stock_fundamentals/fundamentals_20231024.rds",tf)
f_df <- readRDS(tf)

f_df %>% glimpse() 
```
:::

::: {.callout-caution title="In-Class Exercise (Individual)" collapse="false"}
Prepare three simple but striking analyses using `dplyr` on your proposed data sets in Assignment 1. Open a new \.qmd document named `inclass1.qmd` and make it visible on your PJ (update `_quarto.yml` file).
:::

# Week 1

- [Introduction to BDA 503](./intro.html)
- [Base R Notes](https://berkorbay.github.io/book-of-eda/base-r.html)
- [Base R in Detail Notes](https://berkorbay.github.io/book-of-eda/base-r-in-detail.html)
- [Quarto - Getting Started](https://quarto.org/docs/get-started/)

::: {.callout-tip title="Week 1 - Bonus Material" collapse="true"}
- [Intro to R Presentation (Archive)](https://pjournal.github.io/docs/r_intro/2109/#1)
- You can try to code these challenges in R
    - [Euler Project](https://projecteuler.net/archives)
    - [Practice Python](https://www.practicepython.org/)
- Turkish R resource: [Eskişehir R User Group](https://www.youtube.com/@eskisehirrusergroup2103)
:::

::: {.callout-caution title="Assignment 1" collapse="true"}

RMarkdown/Quarto Assignment (Deadline Oct 26, 18:30): This is your first assignment.

1. Prepare a Quarto (.qmd) document. 
2. Introduce yourself in one paragraph (Your name surname, your work, your data interests and how you (plan to) use data science skills in your current/future work). Add your Linkedin account link.
3. Watch some demo and tutorial videos from [Posit Youtube channel playlist](https://youtube.com/playlist?list=PL9HYL-VRX0oTOK4cpbCbRk15K2roEgzVW&si=o2Vh9XiQT_pnMo_B) and write one of them down on your Quarto document. 
4. Propose a dataset (provide a link to source) which we should use in the class for demonstration and teaching purposes. Briefly explain the educational value of the dataset.
5. Find 3 R posts relevant to your interests and describe them. Get the html output and put it in your progress journal repository.
6. Provide a link from your Progress Journal page.

Example Progress Journals from previous year: [Berk Özcan](https://pjournal.github.io/mef06-berkozzcan/assignment1.html) - [Uğur Özata](https://pjournal.github.io/mef06-ugemir/assignment1.html) - [Mehmet Kemal Ucuzcu](https://pjournal.github.io/mef06-mekucz/assignment1.html)
:::

# Week 0

This course benefits from DataCamp for the Classroom program. See details [here](https://www.datacamp.com/groups/education?ref=mefbda503).

Some light reading (blog posts)

-   [Instructor's opinion about GPT use for the classroom](https://medium.com/databulls/gpt-for-education-is-plain-awesome-3663b55887af)
-   [About recent developments with RStudio (Posit) and R's future (2022)](https://medium.com/berk-orbay/convergence-of-data-science-languages-ff2214665f3)
-   [Student projects of previous years (2020)](https://medium.com/berk-orbay/student-data-analysis-projects-with-r-729a8529d5a8)
-   [How this course is structured in previous years (2018)](https://medium.com/@berk.orbay/how-to-teach-an-awesome-data-analysis-course-922f5e5651c0)
-   [Instructor's view on R (2017)](https://medium.com/yes-r-can/why-r-stats-is-the-best-2c09d77de25b)

This semester course webpage went under a significant refurbishment. Course archive is in another repository.

-   [Course Archive](https://mef-bda503.github.io/archive/)
